apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-graphql
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cms-graphql
  template:
    metadata:
      labels:
        app: cms-graphql
    spec:
      containers:
        - image: mexverse/verse-cms-graphql:latest
          name: cms-graphql
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
